---
collections:
- name: https://storage.googleapis.com/ace-box-public-roles/ace_box-tools-0.0.0.tar.gz
  source: url
- name: https://storage.googleapis.com/ace-box-public-roles/ace_box-apps-0.0.0.tar.gz
  source: url
